-- GERAÇÃO DAS COMBINAÇÕES 6 A 6 DOS VALORES EM T, TAL QUE LENGTH(T) >= 6
DROP TABLE IF EXISTS T;
CREATE TEMP TABLE T (
  N INTEGER NOT NULL UNIQUE ON CONFLICT ABORT CHECK(N BETWEEN 1 AND 60)
);
INSERT INTO T VALUES (1), (7), (5), (4), (8), (3), (6), (2); --> exemplo
CREATE TEMP VIEW IF NOT EXISTS COMBO AS
  WITH V AS (
    SELECT * FROM T ORDER BY N ASC
  ) SELECT A.N N1, B.N N2, C.N N3, D.N N4, E.N N5, F.N N6
      FROM V A JOIN V B ON A.N < B.N
        JOIN V C ON B.N < C.N
        JOIN V D ON C.N < D.N
        JOIN V E ON D.N < E.N
        JOIN V F ON E.N < F.N;
SELECT * FROM COMBO;
